project_id = "qwbierwmjdxtlwnncgdp"

[functions.generate-goal-report]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.manage-invitation]
verify_jwt = false
